# Generated by ./gen-packages.sh
{ mkDerivation, amazonka-core, amazonka-test, base, bytestring
, case-insensitive, fetchzip, lib, tasty, tasty-hunit, text, time
, unordered-containers
}:
mkDerivation {
  pname = "amazonka-s3";
  version = "2.0";
  src = fetchzip {
    url = "https://github.com/brendanhay/amazonka/archive/a7d699be1076e2aad05a1930ca3937ffea954ad8.zip";
    sha256 = "034d9rni0n95qmbc6fr13b7kbrs5s9s5qarg7znwx068gwf6293h";
  };
  postUnpack = "sourceRoot+=/lib/services/amazonka-s3; echo source root reset to $sourceRoot";
  libraryHaskellDepends = [ amazonka-core base text ];
  testHaskellDepends = [
    amazonka-core amazonka-test base bytestring case-insensitive tasty
    tasty-hunit text time unordered-containers
  ];
  homepage = "https://github.com/brendanhay/amazonka";
  description = "Amazon Simple Storage Service SDK";
  license = lib.licenses.mpl20;
}
