# Generated by ./gen-packages.sh
{ mkDerivation, aeson, attoparsec, base, bytestring
, case-insensitive, conduit, conduit-extra, containers, crypton
, data-ordlist, deepseq, fetchzip, hashable, http-client
, http-conduit, http-types, lib, memory, microlens
, microlens-contra, microlens-pro, QuickCheck, quickcheck-unicode
, regex-posix, resourcet, scientific, tasty, tasty-hunit
, tasty-quickcheck, template-haskell, text, time, transformers
, unordered-containers, xml-conduit, xml-types
}:
mkDerivation {
  pname = "amazonka-core";
  version = "2.0";
  src = fetchzip {
    url = "https://github.com/brendanhay/amazonka/archive/a7d699be1076e2aad05a1930ca3937ffea954ad8.zip";
    sha256 = "034d9rni0n95qmbc6fr13b7kbrs5s9s5qarg7znwx068gwf6293h";
  };
  postUnpack = "sourceRoot+=/lib/amazonka-core; echo source root reset to $sourceRoot";
  libraryHaskellDepends = [
    aeson attoparsec base bytestring case-insensitive conduit
    conduit-extra containers crypton deepseq hashable http-client
    http-conduit http-types memory microlens microlens-contra
    microlens-pro regex-posix resourcet scientific text time
    transformers unordered-containers xml-conduit xml-types
  ];
  testHaskellDepends = [
    aeson base bytestring case-insensitive conduit data-ordlist
    http-conduit http-types QuickCheck quickcheck-unicode tasty
    tasty-hunit tasty-quickcheck template-haskell text time
  ];
  homepage = "https://github.com/brendanhay/amazonka";
  description = "Core data types and functionality for Amazonka libraries";
  license = lib.licenses.mpl20;
}
