# Generated by ./gen-packages.sh
{ mkDerivation, aeson, amazonka, amazonka-core, amazonka-s3
, auto-update, barrier, base, blaze-html, blaze-markup, bytestring
, Cabal, casa-client, classy-prelude, classy-prelude-conduit
, classy-prelude-yesod, cmark-gfm, conduit, conduit-extra
, containers, deepseq, directory, email-validate, esqueleto
, exceptions, fast-logger, file-embed, filepath, formatting, gauge
, ghc-prim, haddock-library, hashable, hoogle, hpack, html-conduit
, http-client, http-conduit, http-types, lens, lib, monad-logger
, mono-traversable, mtl, optparse-applicative, pantry, path
, path-io, path-pieces, persistent, persistent-postgresql
, persistent-sqlite, persistent-template, process, resource-pool
, resourcet, retry, rio, shakespeare, streaming-commons
, tar-conduit, template-haskell, text, these, transformers
, unliftio, unordered-containers, wai, wai-extra, wai-logger, warp
, xml-conduit, xml-types, yaml, yesod, yesod-auth, yesod-core
, yesod-form, yesod-gitrepo, yesod-gitrev, yesod-newsfeed
, yesod-sitemap, yesod-static, zlib
}:
mkDerivation {
  pname = "stackage-server";
  version = "0.0.0";
  src = ../.;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    aeson amazonka amazonka-core amazonka-s3 auto-update barrier base
    blaze-html blaze-markup bytestring Cabal classy-prelude
    classy-prelude-conduit classy-prelude-yesod cmark-gfm conduit
    conduit-extra containers deepseq directory email-validate esqueleto
    exceptions fast-logger file-embed filepath formatting ghc-prim
    haddock-library hashable hoogle html-conduit http-client
    http-conduit http-types lens monad-logger mono-traversable mtl
    pantry path path-pieces persistent persistent-postgresql
    persistent-sqlite persistent-template process resource-pool
    resourcet retry rio shakespeare streaming-commons tar-conduit
    template-haskell text these transformers unliftio
    unordered-containers wai wai-extra wai-logger warp xml-conduit
    xml-types yaml yesod yesod-auth yesod-core yesod-form yesod-gitrepo
    yesod-gitrev yesod-newsfeed yesod-sitemap yesod-static zlib
  ];
  libraryToolDepends = [ hpack ];
  executableHaskellDepends = [
    aeson amazonka amazonka-core amazonka-s3 auto-update barrier base
    blaze-html blaze-markup bytestring Cabal classy-prelude
    classy-prelude-conduit classy-prelude-yesod cmark-gfm conduit
    conduit-extra containers deepseq directory email-validate esqueleto
    exceptions fast-logger file-embed filepath formatting ghc-prim
    haddock-library hashable hoogle html-conduit http-client
    http-conduit http-types lens monad-logger mono-traversable mtl
    optparse-applicative pantry path path-pieces persistent
    persistent-postgresql persistent-sqlite persistent-template process
    resource-pool resourcet retry rio shakespeare streaming-commons
    tar-conduit template-haskell text these transformers unliftio
    unordered-containers wai wai-extra wai-logger warp xml-conduit
    xml-types yaml yesod yesod-auth yesod-core yesod-form yesod-gitrepo
    yesod-gitrev yesod-newsfeed yesod-sitemap yesod-static zlib
  ];
  benchmarkHaskellDepends = [
    aeson amazonka amazonka-core amazonka-s3 auto-update barrier base
    blaze-html blaze-markup bytestring Cabal casa-client classy-prelude
    classy-prelude-conduit classy-prelude-yesod cmark-gfm conduit
    conduit-extra containers deepseq directory email-validate esqueleto
    exceptions fast-logger file-embed filepath formatting gauge
    ghc-prim haddock-library hashable hoogle html-conduit http-client
    http-conduit http-types lens monad-logger mono-traversable mtl
    pantry path path-io path-pieces persistent persistent-postgresql
    persistent-sqlite persistent-template process resource-pool
    resourcet retry rio shakespeare streaming-commons tar-conduit
    template-haskell text these transformers unliftio
    unordered-containers wai wai-extra wai-logger warp xml-conduit
    xml-types yaml yesod yesod-auth yesod-core yesod-form yesod-gitrepo
    yesod-gitrev yesod-newsfeed yesod-sitemap yesod-static zlib
  ];
  prePatch = "hpack";
  license = lib.licenses.mit;
}
