{{- if .Values.ingress.enabled -}}
{{- $name := .Values.name -}}
{{- $hoogleName := .Values.hoogleName -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $name }}
  labels:
    app: {{ .Values.app }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- range .Values.ingress.hosts }}
  rules:
    - host: {{ . }}
      http:
        paths:
          - path: /haddock.*
            backend:
              serviceName: {{ $name }}
              servicePort: 80
          - path: /.+/hoogle
            backend:
              serviceName: {{ $hoogleName }}
              servicePort: 80
          - backend:
              serviceName: {{ $name }}
              servicePort: 80
  {{- end }}
  tls:
    - hosts:
      {{- range .Values.ingress.hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ $name }}-tls
{{- end }}
