((haskell-mode . ((haskell-indent-spaces . 4)
                  (haskell-process-type . cabal-repl)
                  (haskell-process-use-ghci . t)))
 (hamlet-mode . ((hamlet/basic-offset . 4)
                 (haskell-process-use-ghci . t)))
 (html-mode . ((haskell-process-use-ghci . t)))
 (css-mode . ((haskell-process-use-ghci . t))))
