# As this is built on NixOS stable, it has to stay on a GHC that exists on the
# OS.
# I.e. changes here need to be synced with changes to
# https://github.com/haskellfoundation/hf-infrastructure
resolver: lts-22.4
extra-deps:
# WARNING: Changing the hoogle version causes stackage-server-cron to regenerate
# Hoogle databases FOR EVERY SNAPSHOT, EVER. Usually, that's ok! But don't
# forget! The consequences are: (1) More disk usage. Hoogle databases are not
# cleaned up on the stackage-server-cron side, nor on the stackage-server side.
# (Yet. This will change.) (2) More bucket usage. While it's easy to say it's a
# drop in the literal bucket, such excessive misuse of storage makes
# administration, backups, disaster recovery, and many other DevOps concerns
# harder and harder. All but the latest LTS's database are literally never used
# anyway. (3) The Hoogle database schema is defined by the first three
# version components. Any more frequent regeneration is pure unadulterated
# waste. (4) Stackage's Hoogle search will be unavailable until the new
# databases have been generated.
- hoogle-5.0.18.4@sha256:1372458e97dff541fcda099236af7936bf93ee6b8c5d15695ee6d9426dff5eed,3171
- git: https://github.com/commercialhaskell/pantry.git
  commit: 5df643cc1deb561d9c52a9cb6f593aba2bc4c08e
# This amazonka patched to support Cloudflare, which kinda has a bug. See
# https://github.com/brendanhay/amazonka/issues/975 for details.
- github: chreekat/amazonka
  commit: '85e0289f8dc23c54b00f7f1a09845be7e032a1eb'
  subdirs: [lib/amazonka-core]

allow-newer: true
allow-newer-deps:
  - pantry

nix:
  packages:
    - zlib
    - postgresql
    - pkg-config
    - haskell-language-server
    - cacert
