FROM docker.pkg.github.com/fpco/stackage-server/base-build:a5562eea85c1b0646c35ad924511a90c2a40a2f3 as build-app

RUN mkdir -p /artifacts/bin
COPY . /src
RUN stack install --stack-yaml /src/stack.yaml --local-bin-path /artifacts/bin

FROM docker.pkg.github.com/fpco/stackage-server/base-run:c0e6c9d09198bb661919366a07351c334d7caeb0

COPY --from=build-app /src/config/ /app/config/
COPY --from=build-app /src/static/ /app/static/
COPY --from=build-app /artifacts/bin/stackage-server /usr/local/bin/stackage-server
COPY --from=build-app /artifacts/bin/stackage-server-cron /usr/local/bin/stackage-server-cron
