FROM fpco/pid1:18.04

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install libpq-dev curl git -y && \
    curl -sSL https://get.haskellstack.org/ | sh && \
    unset DEBIAN_FRONTEND
